---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.0.15' }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu-14.04
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[database_sl::postgresql]
      - recipe[database_sl::postgresql_test]
    attributes:

